### PR TITLE
Adapt high-availability configuration

### LINKED ISSUE #15: Create a pod disruption budget for the OWA deployment
**What would you like to be added**:
Pod disruption budget for the `oidc-webhook-authenticator` deployment to be specified on extension enablement.

**Why is this needed**:
Disruption in the operations of the OWA can cause downtime for the end user meaning that he will not be able to authenticate against the cluster with tokens issued from a trusted identity provider. This is why it is important for the OWA to be highly available.

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area high-availability
/kind enhancement

**What this PR does / why we need it**:
This PR prepares components for HA by labeling them with the corresponding `high-availability-config.resources.gardener.cloud/type` and defining the required `PodDisruptionBudget`, please see [this document](https://github.com/gardener/gardener/blob/master/docs/development/high-availability.md) for more information.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6529
Fixes #15

**Release note**:

```feature operator
Extension and control-plane components have been adjusted to the high availability configuration supported by Gardener as of release `v1.60`. See [this document](https://github.com/gardener/gardener/blob/master/docs/development/high-availability.md) for more information about HA in gardener.
```
```feature user
This release adds HA support for the service's control-plane components when extension is deployed along with Gardener >= `v1.60`. Please see [this document](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_high_availability.md) for more information about HA settings in shoot clusters.
```

### CODE REVIEW

**Comment by dimityrmirchev** [comment]
Thanks! I will review as soon as I have the time. I guess this will also complete https://github.com/gardener/gardener-extension-shoot-oidc-service/issues/15

**Review by dimityrmirchev — CHANGES_REQUESTED** [review]
I did some testing against the latest g/g branch (provider-local) and I found some small issues. OWA is scaled horizontally with a HPA resource [ref](https://github.com/gardener/gardener-extension-shoot-oidc-service/blob/e99cea729dabbd5ace1d0a837c64edbf42dee848/pkg/controller/lifecycle/actuator.go#L579). This leads to the deployment constantly scaled from 2 to 1 and back to 2.

```
34s         Normal    SuccessfulDelete               replicaset/oidc-webhook-authenticator-88f99dff7      Deleted pod: oidc-webhook-authenticator-88f99dff7-4l7h7
34s         Normal    SuccessfulCreate               replicaset/oidc-webhook-authenticator-88f99dff7      (combined from similar events): Created pod: oidc-webhook-authenticator-88f99dff7-5xgbt
34s         Normal    ScalingReplicaSet              deployment/oidc-webhook-authenticator                Scaled up replica set oidc-webhook-authenticator-88f99dff7 to 2
34s         Normal    ScalingReplicaSet              deployment/oidc-webhook-authenticator                Scaled down replica set oidc-webhook-authenticator-88f99dff7 to 1
34s         Normal    SuccessfulRescale              horizontalpodautoscaler/oidc-webhook-authenticator   New size: 1; reason: All metrics below target
```
After a while the replicas even stay at 1. Notice that the same is also happening for the `kube-apiserver`.
```
$ k -n shoot--local--local get hpa
NAME                         REFERENCE                               TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
kube-apiserver-nh8s7         Deployment/kube-apiserver               21%/80%   1         4         1          47m
oidc-webhook-authenticator   Deployment/oidc-webhook-authenticator   8%/80%    1         3         1          45m
```

My straightforward thoughts are that we can set the minPods of the hpa object to `2`. But then this will mean that OWA is deployed with a minimum of 2 replicas even if the GRM ha webhook is not mutating the deployment. WDYT?

**Comment by timuthy** [comment]
Mentioned scale-down issue is tackled in a2569be46a0fcfa1626dca0dc35408703de881b6. Let's wait until Gardener `v1.63.x` is released which will include the webhook handling support for `HPA` resources.
/hold

**Review by dimityrmirchev — APPROVED** [review]
Since gardener v1.63.0 was released we can move forward with this PR.
/unhold
/lgtm

**Pull request merged**
