### PR TITLE
Add e2e tests with provider local

### PR DESCRIPTION
**Pull request by dimityrmirchev**
**What this PR does / why we need it**:
Add e2e test run implementation.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user
E2E tests using Gardener's `provider-local` are now being executed on every PR.
```

### CODE REVIEW

**Comment by timebertt** [comment]
Just checked your test result, seems like you're a few steps further now :)

```
retry failed with context deadline exceeded, last error: could not construct Shoot client: error discovering kubernetes version: Get "https://api.local.local.external.local.gardener.cloud/version?timeout=32s": dial tcp: lookup api.local.local.external.local.gardener.cloud on 100.64.0.10:53: no such host
  occurred
```

This error is caused by the limitation of the current DNS setup in provider-local: https://github.com/gardener/gardener/blob/master/docs/extensions/provider-local.md#current-limitations
In gardener-e2e-kind we don't need to access the created test shoot, so we set `SkipAccessingShoot=true`: https://github.com/gardener/gardener/blob/80c9a619e3d5e68f6fb5a4fcdb016004c34fbc64/test/e2e/shoot/common.go#L47

If your case still requires accessing the test shoot, you might need to fake some hostname look ups in the test code / test framework to point the external shoot domain to `127.0.0.1` (just like we do in the [local setup](https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md#creating-a-shoot-cluster) via `/etc/hosts`). (BTW: this is also required for https://github.com/gardener/gardener/issues/5586)

For now, in order to get your test job to work in the first place via some hacks, you could consider to simply append `/etc/hosts` as well :)

**Comment by dimityrmirchev** [comment]
Thanks! I thought this might be the case. I am now trying to implement my own test suite that will have separated scenarios instead of one test that tries to cover them all. For some of these I will not need the shoot client, but I will need to verify some resources in the seed. As for the hacks, I can look into that later on. But even without it if I manage to run the other scenarios that will already be a HUGE step forward :)

**Review by vpnachev — APPROVED** [review]
/lgtm

**Review by vpnachev — APPROVED** [review]
/lgtm

**Pull request merged**
