### PR TITLE
Add check for docforge manifest files

### PR DESCRIPTION
**Pull request by dimityrmirchev**
**What this PR does / why we need it**:
Adds a step to verify the validity of the docforge manifest files.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user

```

### CODE REVIEW

**Review by vpnachev — APPROVED** [review]
/lgtm

**Review by Kristian-ZH — APPROVED** [review]
Thanks for the PR!

/lgtm

**Review by vpnachev — APPROVED** [review]
/lgtm

**Pull request merged**
